// Generated by sweetyx
interface sharkOptions {
}

interface JQuery {
    sharkAutoComplete(sharkOptions?: sharkOptions): JQuery;
    sharkDropdown(sharkOptions?: sharkOptions): JQuery;
    sharkFileupload(sharkOptions?: sharkOptions): JQuery;
    sharkModal(sharkOptions?: sharkOptions): JQuery;
    sharkPager(sharkOptions?: sharkOptions): JQuery;
    sharkPopover(sharkOptions?: sharkOptions): JQuery;
    sharkSelecter(sharkOptions?: sharkOptions): JQuery;
    sharkTabs(sharkOptions?: sharkOptions): JQuery;
    sharkTooltip(sharkOptions?: sharkOptions): JQuery;
    sharkTree(sharkOptions?: sharkOptions): JQuery;
    sharkToastr(sharkOptions?: sharkOptions): JQuery;
}

